version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserverdb
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "YourStrong@Passw0rd", "-Q", "SELECT 1"]
      interval: 10s
      retries: 10
    networks:
      app-network:
        ipv4_address: 172.20.0.4

  frontend:
    container_name: aayush_frontend
    build:
      context: ..
      dockerfile: DevOps/Dockerfile.frontend
    ports:
      - "80:80"
    networks:
      app-network:
        ipv4_address: 172.20.0.2
    volumes:
      - ../frontend/dist:/app/dist

  backend:
    container_name: aayush_backend
    build:
      context: ..
      dockerfile: DevOps/Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8000
      - JWT_ISSUER=http://localhost:8000
      - JWT_AUDIENCE=http://localhost:3000
    networks:
      app-network:
        ipv4_address: 172.20.0.3

  nginx:
    build:
      context: ..
      dockerfile: DevOps/Dockerfile.nginx
    ports:
      - "5007:80" 
    networks:
      app-network:
        ipv4_address: 172.20.0.5
    volumes:
      - ../frontend/dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
volumes:
  mssql_data:

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1